### ISSUE TITLE
AppImages are supposed to be cross-distro and require no installation

### ISSUE THREAD

**Issue by probonopd** [Adriex/Kritabuntu#1]
As should be evident from the [stated goals](https://github.com/probonopd/AppImageKit/blob/master/README.md), AppImages are supposed to be cross-distro and require no installation.

If by "installation" you mean desktop integration, have a look at the upcoming optional `appimaged` daemon which will handle this for you automatically.

Like this:
https://www.youtube.com/watch?v=FqVAtHdK1N0

https://github.com/probonopd/appimagetool

**Comment by Adriex** [comment]
Hi, im just updated the reposoitory with more info about it. And the appimaged daemon... seriusly, i searched a lot for find something like that! It is what i wanted to do (but just with krita) Thank you! But, that mean i have to delete my repo?

**Comment by Adriex** [comment]
By the way, i have been testing ```appimaged``` with krita and this comes out:
```
-> REGISTER /usr/local/bin/krita.appimage
ISO9660 based type 1 AppImage, not yet implemented: /usr/local/bin/krita.appimage
```
Krita doesn't show in menus. Did i miss something?

**Comment by probonopd** [comment]
ISO9660 based type 1 AppImages are currently not supported by appimaged, only the newer type 2 AppImages.

**Comment by Adriex** [comment]
Ok, by now i will use my way and i will modify the Readme so anyone looking for an appimage desktop integration for another app can use ```appimaged```

**Comment by probonopd** [comment]
Thanks

**Comment by Adriex** [comment]
by the way, how did you find my repository so fast?

**Comment by probonopd** [comment]
Just interested in what people do with AppImage, so checked GitHub :-)
